portfolio_general:
    resource: "@portfolioGeneralBundle/Resources/config/routing.yml"
    prefix:   /

portfolio_user:
    resource: "@PortfolioUserBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
