portfolio_project:
    resource: "@portfolioProjectBundle/Resources/config/routing.yml"
    prefix:   /

portfolio_general:
    resource: "@portfolioGeneralBundle/Resources/config/routing.yml"
    prefix:   /

portfolio_user:
    resource: "@PortfolioUserBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

mremi_contact_form:
    resource: "@MremiContactBundle/Resources/config/routing.xml"